### PR TITLE
Add LICENSE file

### LINKED ISSUE #2: License
It look like this doesn't have any license. What license do you plan to have?

### PR DESCRIPTION
**Pull request by hajimehoshi**
Fixes #2

### CODE REVIEW

**Review by j7b — COMMENTED** [review]
Copyright 2017 the Ebiten Authors ok?

**Comment by hajimehoshi** [comment]
Ok but Apache 2.0 LICENSE file itself doesn't have to imply the author IIUC

**Comment by j7b** [comment]
line 189

**Comment by hajimehoshi** [comment]
That's just a template in an appendix. It's ok to leave as it is.

e.g. https://github.com/google/iosched/blob/master/LICENSE

**Review by j7b — APPROVED** [review]
👍

**Pull request merged**
