### PR TITLE
Bug fix: Remove CSS font size for the editor

### PR DESCRIPTION
**Pull request by hajimehoshi**
This PR fixes a problem that the editor's font size is not reset when the default program is used.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Hm, this still has a problem when the font size is 12.

**Comment by hajimehoshi** [comment]
@j7b , can you take a look? Thanks.

**Review by j7b — APPROVED** [review]
👍

**Comment by hajimehoshi** [comment]
Thank you!

**Pull request merged**
